apiVersion: v2
name: pet-battle-api
description: ðŸ¦© Pet Battle API ðŸ¦©
type: application
version: 1.0.6
appVersion: 1.0.0
home: https://eformat.github.io/helm-charts
icon: https://avatars1.githubusercontent.com/u/68044996?s=200&v=4
kubeVersion: '>=1.11.0-0'
keywords:
- devops
- petbattle
maintainers:
- name: eformat
