apiVersion: v2
name: pet-battle-api
description: A Helm chart for Kubernetes
type: application
version: 1.0.2
appVersion: 1.0.0
home: https://eformat.github.io/helm-charts
maintainers:
- name: eformat
