# Default values for pet-battle-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# OpenShift objects
route: true
# if false use a kube deployment instead
deploymentConfig: false
replicas:
  min: 2
  max: 6
image_repository: quay.io
image_name: pet-battle-api
image_namespace: petbattle
image_version: latest
hpa:
  enabled: true
  cpuTarget: 200m
  memTarget: 300Mi
# use the image specified above as tag (else tag overridden in pipeline say)
istag:
  enabled: true
# not safe for families service
nsff:
  enabled: false
  apiHost: tensorflowserving-pb-nsff
  apiPort: 8501
  limit: 0.6

# do we deploy mongodb from a template (not helm chart)
mongodbTemplate:
  enabled: true
  database:
    name: cats
    adminPassword: password
    user: user
    password: password
  image: mongodb:3.6
  storage: 1Gi
# mongodb subchart values (not used at present)
mongodb-replicaset:
  securityContext:
    runAsUser: '1000850000'
    fsGroup: '1000850000'
  persistentVolume:
    enabled: true
    storageClass: gp2
    size: 1Gi
  auth:
    enabled: true
    adminUser: admin
    adminPassword: password
    key: |
      EQa74ITas01uOJarj5rAcmkVIIpsOGRd+tFXwiB02R9ilY1zUvSHYK/+yicvlDr4
      YdvHaK+cVU3SuiLA4BJ5ASK4Y9nbU/RNCZeTGHCdzD+B3IG2bFdt6MyTSfdo/evO
      T/W1Zq6Ema247MqQtogsKv2gz0OciMs7lES/rfezKt5lXDFm0+VB2h7wiaY5zbWR
      TbzfulAdjjQH47XpjnwnQO1deWQSAaL6DLc4/KJ3eTg6OazI93YFIx5FIBl92zQY
      3xZM5ZYN20nWXeV9En9tlacC+kme1lO0rh3GztpbWzfdI2UEOfTniM3mtiNu7YUw
      LV/rkIiiM73GlSg0ub06VLGpLwQjdH1ayAXypRvlkf54KSq2mFgt3hRAbfzHpg2l
      r+qhVRhvrIk4+UXcJN1c1v+DvPF6WJrIsD2H15fljqzeolLbl5rWbWoZsO4fJYsv
      0mZ492/tUzNrJcb0el4SdPGjzu+D+gU/dQlhYiscWrkZ1jLG1/R4w0gIvn6JDPNc
      dy7qsA3qzgHP+aP9tR7l1tr1iBAebAkskAN+HOnpMHyFoC3TxLiKelAxJ57blh73
      CeX2lDILKxPc3wmXo6SZrKmcL59BX9HlwyRfLA95gqST9pKkeAtj60rj7LIUFUyy
      tzOiOwgisIxbl0O9K9VmBEZ1KVZSeJJi1s5dm8VTAowb756sal4nJnBY2/GcQuqr
      MaF1iqaZTTfd0omNTLV6Gvr4ObfbvEqsISf52cqbrfNjytXdGjpqGGxpXp/Xm8Yz
      3tFJy8PMJKZ4qVFtPvSfEZ28NUzTfNT5wifqBjhfRqXpVnLP0aoj5hjRcxqmFDC8
      ozWr6NJqdmSvpENuf25uQggl6/GzDGgsWXesdu5orrjYZy8SfMjA1284vvpxYayu
      VMJ1b4KUtqwWMG1WKCoe1GJThjFKq0JDEboWxUmvmU5ng9LttdjfKu8vdDOjSImO
      GZHXvHfvLMq/FWBETJ0I23qFtSN888LZNXsu6odwk/19aYmL

# service mesh
istio:
  enabled: false
  mtls: true
  domain: apps.hivec.sandbox209.opentlc.com
