apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-battle-api-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pet-battle-api-operator
  template:
    metadata:
      labels:
        name: pet-battle-api-operator
    spec:
      serviceAccountName: pet-battle-api-operator
      containers:
        - name: pet-battle-api-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pet-battle-api-operator"
