---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "pet-battle-api.fullname" . }}
  labels:
    {{- include "pet-battle-api.labels" . | nindent 4 }}
  creationTimestamp: null
spec:
  lookupPolicy:
    local: false
{{- if (eq .Values.istag.enabled true) }}
  tags:
    - annotations:
        openshift.io/imported-from: eformat/pet-battle-api
      from:
        kind: DockerImage
        name: {{ .Values.image_repository }}/{{ .Values.image_namespace }}/{{ .Values.image_name }}:{{ .Values.image_version }}
      importPolicy: {}
      name: {{ .Values.image_version }}
{{ end }}
